name: test
on:
  push:
    branches:
    - "master"
  pull_request: {}
jobs:
  list:
    name: List Perl Versions
    runs-on: ubuntu-latest
    steps:
    - uses: shogo82148/actions-setup-perl@v1
    - name: list available perl versions
      id: set-matrix
      shell: perl {0}
      run: |
        use Actions::Core;
        my ($latest, $prev) = perl_versions();
        set_output(perl => [$latest, $prev]);
    outputs:
      perl: ${{ steps.set-matrix.outputs.perl }}
  test:
    name: Run Test with Perl ${{ matrix.perl }} on ${{ matrix.runner }}
    needs: list
    strategy:
      fail-fast: false
      matrix:
        perl: ${{fromJson(needs.list.outputs.perl)}}
        runner: [ubuntu-latest, macos-latest]  # , windows-latest
    runs-on: ${{matrix.runner}}
    steps:
    - uses: actions/checkout@v4
    - name: Setup perl
      uses: shogo82148/actions-setup-perl@v1
      with:
        perl-version: ${{ matrix.perl }}
    - name: Install Modules
      run: |
        cpanm --quiet --installdeps --notest --with-configure --with-develop .
    - run: |
        perl Build.PL && ./Build build && ./Build test
